import WebSocket from 'ws';
import { PROTOCOL_VERSION } from './shared/constants.js';
const ws = new WebSocket('ws://localhost:8090');
const inbox = []; let ok = 0, ko = 0;
const check = (n, c) => { console.log((c ? '  ✔ ' : '  ✘ ') + n); c ? ok++ : ko++; };
const texts = (m) => m.t === 'events' ? (m.list || []).map(e => e.text || '') : [m.text || ''];
const wait = (re, ms = 2500) => new Promise(res => { const t0 = Date.now();
  const iv = setInterval(() => { const hit = inbox.some(m => texts(m).some(t => re.test(t)));
    if (hit || Date.now() - t0 > ms) { clearInterval(iv); res(hit); } }, 40); });
const send = (m) => ws.send(JSON.stringify(m));
const pause = (ms = 950) => new Promise(r => setTimeout(r, ms));
const goto_ = async (x, z) => { send({ t: 'admin', cmd: 'goto', x, z }); await pause(300); };
const say = async (t) => { await pause(); inbox.length = 0; send({ t: 'chat', text: t }); };
ws.on('message', (raw, bin) => { if (!bin) inbox.push(JSON.parse(raw.toString())); });
ws.on('open', () => send({ t: 'register', v: PROTOCOL_VERSION, name: 'Heros' + (Math.random() * 1e6 | 0), pass: 'test1234' }));
await new Promise(res => { const iv = setInterval(() => {
  if (inbox.some(m => m.t === 'create_char')) send({ t: 'create', stats: { str: 22, end: 18, agi: 14, int: 8, wis: 8 } });
  if (inbox.some(m => m.t === 'welcome')) { clearInterval(iv); res(); } }, 50); });

await goto_(326, 242);
await say('Je cherche du travail');
check('Q1 : Aldric envoie vers Cathbad (+or +xp)', await wait(/Cathbad/));
await say('du travail encore ?');
check('Q1 fait : rappel sans double récompense', await wait(/pierres levées/));
await goto_(327, 62);
await say('parle-moi de la prophetie');
check('Q2 : Cathbad évoque la prophétie', await wait(/murmure/));
await say('ma valeur ?');
check('Q2 : gate de niveau (refus avant le 4)', await wait(/niveau 4/));
send({ t: 'admin', cmd: 'set', level: 4 });
await say('ma valeur ?');
check('Q2 : validée, envoi vers Kilhiam', await wait(/Kilhiam/));
await goto_(330, 242);
await say('des cuirs ?');
check('Q3 : rappel de chasse sans l\u2019objet', await wait(/preuve de chasse/));
await say('parle-moi de l\u2019ogre');
await pause(800);
check('isolation : « ogre » (Holenarbed) muet au village', !inbox.some(m => texts(m).some(t => /saphir/.test(t))));
await say('une amulette ?');
await pause(800);
check('isolation : « amulette » (Iraltok, autre grappe) muette ici', !inbox.some(m => texts(m).some(t => /crocs|dévoré/.test(t))));
console.log(`\n${ko ? ko + ' ÉCHEC(S)' : 'E2E TRAME OK'} (${ok} ✔)`);
process.exit(ko ? 1 : 0);
