apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t4c-web-data
  namespace: t4c-web
  labels:
    app.kubernetes.io/name: t4c-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Recommandation production : Utiliser un stockage à faible latence IOPS (ex: gp3, standard-rwo, etc.)
  # storageClassName: gp3
